version: '3.8'

services:
  test_php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test_php
    restart: unless-stopped
    working_dir: /var/www/html
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: test_postgres
      DB_PORT: 5432
      DB_DATABASE: test_postgres_db
      DB_USERNAME: laravel
      DB_PASSWORD: password
      QUEUE_CONNECTION: rabbitmq
      CACHE_STORE: redis
      RABBITMQ_HOST: test_rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      REDIS_HOST: test_keydb
      REDIS_PORT: 6379
    volumes:
      - .:/var/www/html
    networks:
      - test_net
    depends_on:
      - test_postgres
      - test_rabbitmq
      - test_keydb

  test_nginx:
    image: nginx:alpine
    container_name: test_nginx_server
    restart: unless-stopped
    ports:
      - "3100:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - test_php
    networks:
      - test_net

  test_queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test_queue
    restart: unless-stopped
    working_dir: /var/www/html
    command: php artisan queue:work rabbitmq --queue=high,default,delivery_processing --sleep=3 --tries=3 --timeout=90
    environment:
      APP_NAME: Laravel
      APP_ENV: local
      APP_KEY: base64:n6ZKLcXgOg4/7CrrgnGdi0C2cJjKOw7cr0ZMrsRcvZE=
      APP_DEBUG: "true"
      DB_CONNECTION: pgsql
      DB_HOST: test_postgres
      DB_PORT: 5432
      DB_DATABASE: test_postgres_db
      DB_USERNAME: laravel
      DB_PASSWORD: password
      QUEUE_CONNECTION: rabbitmq
      RABBITMQ_HOST: test_rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      LOG_CHANNEL: stack
      CACHE_STORE: file
      SESSION_DRIVER: array
    volumes:
      - .:/var/www/html
    depends_on:
      - test_php
      - test_postgres
      - test_rabbitmq
    networks:
      - test_net

  test_postgres:
    image: postgres:14
    container_name: test_postgres
    environment:
      POSTGRES_DB: test_postgres_db
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: password
    ports:
      - '5480:5432'
    volumes:
      - test_pgdata:/var/lib/postgresql/data
    networks:
      - test_net

  test_rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: test_rabbitmq_server
    restart: unless-stopped
    ports:
      - "5673:5672"
      - "15673:15672"
    networks:
      - test_net

  test_keydb:
    image: eqalpha/keydb:latest
    container_name: test_keydb_server
    restart: unless-stopped
    networks:
      - test_net

volumes:
  test_pgdata:

networks:
  test_net:
    driver: bridge

