version: '3.8'

services:
  ak_techlogistic:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ak_techlogistic_php
    restart: unless-stopped
    working_dir: /var/www/html
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: ak_techlogistic_postgres
      DB_PORT: 5432
      DB_DATABASE: ak_techlogistic_laravel
      DB_USERNAME: laravel
      DB_PASSWORD: password
      QUEUE_CONNECTION: rabbitmq
      CACHE_STORE: redis
      RABBITMQ_HOST: ak_techlogistic_rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      REDIS_HOST: ak_techlogistic_keydb
      REDIS_PORT: 6379
    volumes:
      - .:/var/www/html
    networks:
      - ak_techlogistic_net
    depends_on:
      - ak_techlogistic_postgres
      - ak_techlogistic_rabbitmq
      - ak_techlogistic_keydb

  ak_techlogistic_nginx:
    image: nginx:alpine
    container_name: ak_techlogistic_nginx_server
    restart: unless-stopped
    ports:
      - "3100:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - ak_techlogistic
    networks:
      - ak_techlogistic_net

  ak_techlogistic_queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ak_techlogistic_queue
    restart: unless-stopped
    working_dir: /var/www/html
    command: php artisan queue:work rabbitmq --queue=high,default,hold_processing --sleep=3 --tries=3 --timeout=90
    environment:
      APP_NAME: Laravel
      APP_ENV: local
      APP_KEY: base64:n6ZKLcXgOg4/7CrrgnGdi0C2cJjKOw7cr0ZMrsRcvZE=
      APP_DEBUG: "true"
      DB_CONNECTION: pgsql
      DB_HOST: ak_techlogistic_postgres
      DB_PORT: 5432
      DB_DATABASE: ak_techlogistic_laravel
      DB_USERNAME: laravel
      DB_PASSWORD: password
      QUEUE_CONNECTION: rabbitmq
      RABBITMQ_HOST: ak_techlogistic_rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      LOG_CHANNEL: stack
      CACHE_STORE: file
      SESSION_DRIVER: array
    volumes:
      - .:/var/www/html
    depends_on:
      - ak_techlogistic
      - ak_techlogistic_postgres
      - ak_techlogistic_rabbitmq
    networks:
      - ak_techlogistic_net

  ak_techlogistic_postgres:
    image: postgres:14
    container_name: ak_techlogistic_postgres_db
    environment:
      POSTGRES_DB: ak_techlogistic_laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: password
    ports:
      - '5480:5432'
    volumes:
      - ak_techlogistic_pgdata:/var/lib/postgresql/data
    networks:
      - ak_techlogistic_net

  ak_techlogistic_rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: ak_techlogistic_rabbitmq_server
    restart: unless-stopped
    ports:
      - "5673:5672"
      - "15673:15672"
    networks:
      - ak_techlogistic_net

  ak_techlogistic_keydb:
    image: eqalpha/keydb:latest
    container_name: ak_techlogistic_keydb_server
    restart: unless-stopped
    networks:
      - ak_techlogistic_net

volumes:
  ak_techlogistic_pgdata:

networks:
  ak_techlogistic_net:
    driver: bridge

